# coding: utf-8

"""
    Signing Today Web

    *Signing Today* is the perfect Digital Signature Gateway. Whenever in Your workflow You need to add one or more Digital Signatures to Your document, *Signing Today* is the right choice. You prepare Your documents, *Signing Today* takes care of all the rest: send invitations (`signature tickets`) to signers, collects their signatures, send You back the signed document. Integrating *Signing Today* in Your existing applications is very easy. Just follow these API specifications and get inspired by the many examples presented hereafter.   # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import signing_today_client
from signing_today_client.models.notification_event import NotificationEvent  # noqa: E501
from signing_today_client.rest import ApiException

class TestNotificationEvent(unittest.TestCase):
    """NotificationEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test NotificationEvent
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = signing_today_client.models.notification_event.NotificationEvent()  # noqa: E501
        if include_optional :
            return NotificationEvent(
                id = 1, 
                time = '2007-04-02T19:30:10Z', 
                dst_id = 'd6bb4c8f-37bf-4900-a1e4-dd9b0939cafb', 
                user_id = '1ca229c8-2a99-4f3e-9421-36377fd8d9e5', 
                dst_title = 'Contract', 
                username = 'johndoe', 
                email = 'jdo@bit4id.com', 
                event = 'evt_dst_status_signed'
            )
        else :
            return NotificationEvent(
        )

    def testNotificationEvent(self):
        """Test NotificationEvent"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
