# coding: utf-8

"""
    Signing Today Web

    *Signing Today* is the perfect Digital Signature Gateway. Whenever in Your workflow You need to add one or more Digital Signatures to Your document, *Signing Today* is the right choice. You prepare Your documents, *Signing Today* takes care of all the rest: send invitations (`signature tickets`) to signers, collects their signatures, send You back the signed document. Integrating *Signing Today* in Your existing applications is very easy. Just follow these API specifications and get inspired by the many examples presented hereafter.   # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import signing_today_client
from signing_today_client.models.signature_request import SignatureRequest  # noqa: E501
from signing_today_client.rest import ApiException

class TestSignatureRequest(unittest.TestCase):
    """SignatureRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SignatureRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = signing_today_client.models.signature_request.SignatureRequest()  # noqa: E501
        if include_optional :
            return SignatureRequest(
                instance_id = 1, 
                id = 3, 
                reason = 'As the Buyer', 
                description = 'The proponent', 
                signer_id = 2, 
                sign_profile = 'PAdES', 
                with_timestamp = True, 
                declinable = False, 
                restrictions = [
                    signing_today_client.models.signature_restriction.SignatureRestriction(
                        rule = '0', 
                        operator = '0', 
                        value = '0', )
                    ], 
                extra_data = {"st_ticketUrl":"http://signing.today/ticket/8bd4aead-ad37-42bc-b3b0-22ce3d1c9e79"}
            )
        else :
            return SignatureRequest(
        )

    def testSignatureRequest(self):
        """Test SignatureRequest"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
