# coding: utf-8

"""
    Signing Today Web

    *Signing Today* is the perfect Digital Signature Gateway. Whenever in Your workflow You need to add one or more Digital Signatures to Your document, *Signing Today* is the right choice. You prepare Your documents, *Signing Today* takes care of all the rest: send invitations (`signature tickets`) to signers, collects their signatures, send You back the signed document. Integrating *Signing Today* in Your existing applications is very easy. Just follow these API specifications and get inspired by the many examples presented hereafter.   # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import signing_today_client
from signing_today_client.api.notifications_api import NotificationsApi  # noqa: E501
from signing_today_client.rest import ApiException


class TestNotificationsApi(unittest.TestCase):
    """NotificationsApi unit test stubs"""

    def setUp(self):
        self.api = signing_today_client.api.notifications_api.NotificationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_notifications_dst_id_delete(self):
        """Test case for notifications_dst_id_delete

        Clear Notifications for a DST  # noqa: E501
        """
        pass

    def test_notifications_dsts_get(self):
        """Test case for notifications_dsts_get

        Get latest DST Notifications  # noqa: E501
        """
        pass

    def test_notifications_push_token_delete(self):
        """Test case for notifications_push_token_delete

        Clear a registered push notification token  # noqa: E501
        """
        pass

    def test_notifications_push_token_post(self):
        """Test case for notifications_push_token_post

        Register a token for push notifications  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
