# coding: utf-8

"""
    Signing Today Web

    *Signing Today* is the perfect Digital Signature Gateway. Whenever in Your workflow You need to add one or more Digital Signatures to Your document, *Signing Today* is the right choice. You prepare Your documents, *Signing Today* takes care of all the rest: send invitations (`signature tickets`) to signers, collects their signatures, send You back the signed document. Integrating *Signing Today* in Your existing applications is very easy. Just follow these API specifications and get inspired by the many examples presented hereafter.   # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import signing_today_client
from signing_today_client.models.audit_record import AuditRecord  # noqa: E501
from signing_today_client.rest import ApiException

class TestAuditRecord(unittest.TestCase):
    """AuditRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AuditRecord
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = signing_today_client.models.audit_record.AuditRecord()  # noqa: E501
        if include_optional :
            return AuditRecord(
                instance_id = 1, 
                at = '2020-01-17T07:26Z', 
                event = 'stage_signed', 
                signer = signing_today_client.models.signer_record.SignerRecord(
                    name = 'Adam', 
                    surname = 'Smith', 
                    email = 'adam.smith@email.com', 
                    role = 'buyer', 
                    user_uuid = '737dc132-a3f0-11e9-a2a3-2a2ae2dbcce4', ), 
                value = 'utente registrato John Doe (jdo@bit4id.com) ha pubblicato la DST "Contratto" (aeaa6c62-8b59-4fac-9419-8e9a95aea410)
La DST contiene i documenti:
- "Contratto Preliminare" con compilatori [John Doe (jdo@bit4id.com)] e firmatari [Adam Smith (adam.smith@email.com)]', 
                dst_id = '00f462e8-333c-45d6-bdef-95797cc1a2a9', 
                document_id = 2, 
                fillable_form_id = 3, 
                signature_request_id = 1, 
                note_id = 2
            )
        else :
            return AuditRecord(
        )

    def testAuditRecord(self):
        """Test AuditRecord"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
