# coding: utf-8

"""
    Signing Today Web

    *Signing Today* is the perfect Digital Signature Gateway. Whenever in Your workflow You need to add one or more Digital Signatures to Your document, *Signing Today* is the right choice. You prepare Your documents, *Signing Today* takes care of all the rest: send invitations (`signature tickets`) to signers, collects their signatures, send You back the signed document. Integrating *Signing Today* in Your existing applications is very easy. Just follow these API specifications and get inspired by the many examples presented hereafter.   # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from signing_today_client.configuration import Configuration


class DSTNote(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'dst_id': 'str',
        'user_id': 'str',
        'created_at': 'datetime',
        'text': 'str'
    }

    attribute_map = {
        'id': 'id',
        'dst_id': 'dstId',
        'user_id': 'userId',
        'created_at': 'createdAt',
        'text': 'text'
    }

    def __init__(self, id=None, dst_id=None, user_id=None, created_at=None, text=None, local_vars_configuration=None):  # noqa: E501
        """DSTNote - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._dst_id = None
        self._user_id = None
        self._created_at = None
        self._text = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if dst_id is not None:
            self.dst_id = dst_id
        if user_id is not None:
            self.user_id = user_id
        if created_at is not None:
            self.created_at = created_at
        if text is not None:
            self.text = text

    @property
    def id(self):
        """Gets the id of this DSTNote.  # noqa: E501

        The id of the note  # noqa: E501

        :return: The id of this DSTNote.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this DSTNote.

        The id of the note  # noqa: E501

        :param id: The id of this DSTNote.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def dst_id(self):
        """Gets the dst_id of this DSTNote.  # noqa: E501

        The _UUID_ code of the Digital Signature Transaction  # noqa: E501

        :return: The dst_id of this DSTNote.  # noqa: E501
        :rtype: str
        """
        return self._dst_id

    @dst_id.setter
    def dst_id(self, dst_id):
        """Sets the dst_id of this DSTNote.

        The _UUID_ code of the Digital Signature Transaction  # noqa: E501

        :param dst_id: The dst_id of this DSTNote.  # noqa: E501
        :type: str
        """

        self._dst_id = dst_id

    @property
    def user_id(self):
        """Gets the user_id of this DSTNote.  # noqa: E501

        The _UUID_ code of the user which created the _Note_  # noqa: E501

        :return: The user_id of this DSTNote.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this DSTNote.

        The _UUID_ code of the user which created the _Note_  # noqa: E501

        :param user_id: The user_id of this DSTNote.  # noqa: E501
        :type: str
        """

        self._user_id = user_id

    @property
    def created_at(self):
        """Gets the created_at of this DSTNote.  # noqa: E501

        The _data-time_ of the note creation  # noqa: E501

        :return: The created_at of this DSTNote.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this DSTNote.

        The _data-time_ of the note creation  # noqa: E501

        :param created_at: The created_at of this DSTNote.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def text(self):
        """Gets the text of this DSTNote.  # noqa: E501

        Actual content of the _DST Note_  # noqa: E501

        :return: The text of this DSTNote.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this DSTNote.

        Actual content of the _DST Note_  # noqa: E501

        :param text: The text of this DSTNote.  # noqa: E501
        :type: str
        """

        self._text = text

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DSTNote):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DSTNote):
            return True

        return self.to_dict() != other.to_dict()
