# coding: utf-8

"""
    Signing Today Web

    *Signing Today* is the perfect Digital Signature Gateway. Whenever in Your workflow You need to add one or more Digital Signatures to Your document, *Signing Today* is the right choice. You prepare Your documents, *Signing Today* takes care of all the rest: send invitations (`signature tickets`) to signers, collects their signatures, send You back the signed document. Integrating *Signing Today* in Your existing applications is very easy. Just follow these API specifications and get inspired by the many examples presented hereafter.   # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from signing_today_client.configuration import Configuration


class InstantiateDSTTemplate(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'template_patches': 'CreateDigitalSignatureTransaction',
        'roles_mapping': 'list[RobotIdInstantiateRolesMapping]'
    }

    attribute_map = {
        'template_patches': 'templatePatches',
        'roles_mapping': 'rolesMapping'
    }

    def __init__(self, template_patches=None, roles_mapping=None, local_vars_configuration=None):  # noqa: E501
        """InstantiateDSTTemplate - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._template_patches = None
        self._roles_mapping = None
        self.discriminator = None

        if template_patches is not None:
            self.template_patches = template_patches
        if roles_mapping is not None:
            self.roles_mapping = roles_mapping

    @property
    def template_patches(self):
        """Gets the template_patches of this InstantiateDSTTemplate.  # noqa: E501


        :return: The template_patches of this InstantiateDSTTemplate.  # noqa: E501
        :rtype: CreateDigitalSignatureTransaction
        """
        return self._template_patches

    @template_patches.setter
    def template_patches(self, template_patches):
        """Sets the template_patches of this InstantiateDSTTemplate.


        :param template_patches: The template_patches of this InstantiateDSTTemplate.  # noqa: E501
        :type: CreateDigitalSignatureTransaction
        """

        self._template_patches = template_patches

    @property
    def roles_mapping(self):
        """Gets the roles_mapping of this InstantiateDSTTemplate.  # noqa: E501

        Indicates the mapping between the role specified into the template and the actual signer have to sign the _Digital Signature Transaction_  # noqa: E501

        :return: The roles_mapping of this InstantiateDSTTemplate.  # noqa: E501
        :rtype: list[RobotIdInstantiateRolesMapping]
        """
        return self._roles_mapping

    @roles_mapping.setter
    def roles_mapping(self, roles_mapping):
        """Sets the roles_mapping of this InstantiateDSTTemplate.

        Indicates the mapping between the role specified into the template and the actual signer have to sign the _Digital Signature Transaction_  # noqa: E501

        :param roles_mapping: The roles_mapping of this InstantiateDSTTemplate.  # noqa: E501
        :type: list[RobotIdInstantiateRolesMapping]
        """

        self._roles_mapping = roles_mapping

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InstantiateDSTTemplate):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InstantiateDSTTemplate):
            return True

        return self.to_dict() != other.to_dict()
