# coding: utf-8

"""
    Signing Today Web

    *Signing Today* is the perfect Digital Signature Gateway. Whenever in Your workflow You need to add one or more Digital Signatures to Your document, *Signing Today* is the right choice. You prepare Your documents, *Signing Today* takes care of all the rest: send invitations (`signature tickets`) to signers, collects their signatures, send You back the signed document. Integrating *Signing Today* in Your existing applications is very easy. Just follow these API specifications and get inspired by the many examples presented hereafter.   # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from signing_today_client.configuration import Configuration


class RobotConfiguration(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'request_headers': 'dict(str, list[str])',
        'authentication': 'RobotConfigurationAuthentication',
        'webhooks': 'RobotConfigurationWebhooks'
    }

    attribute_map = {
        'request_headers': 'requestHeaders',
        'authentication': 'authentication',
        'webhooks': 'webhooks'
    }

    def __init__(self, request_headers=None, authentication=None, webhooks=None, local_vars_configuration=None):  # noqa: E501
        """RobotConfiguration - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._request_headers = None
        self._authentication = None
        self._webhooks = None
        self.discriminator = None

        if request_headers is not None:
            self.request_headers = request_headers
        if authentication is not None:
            self.authentication = authentication
        if webhooks is not None:
            self.webhooks = webhooks

    @property
    def request_headers(self):
        """Gets the request_headers of this RobotConfiguration.  # noqa: E501

        Eventually the headers the application have to use during requests  # noqa: E501

        :return: The request_headers of this RobotConfiguration.  # noqa: E501
        :rtype: dict(str, list[str])
        """
        return self._request_headers

    @request_headers.setter
    def request_headers(self, request_headers):
        """Sets the request_headers of this RobotConfiguration.

        Eventually the headers the application have to use during requests  # noqa: E501

        :param request_headers: The request_headers of this RobotConfiguration.  # noqa: E501
        :type: dict(str, list[str])
        """

        self._request_headers = request_headers

    @property
    def authentication(self):
        """Gets the authentication of this RobotConfiguration.  # noqa: E501


        :return: The authentication of this RobotConfiguration.  # noqa: E501
        :rtype: RobotConfigurationAuthentication
        """
        return self._authentication

    @authentication.setter
    def authentication(self, authentication):
        """Sets the authentication of this RobotConfiguration.


        :param authentication: The authentication of this RobotConfiguration.  # noqa: E501
        :type: RobotConfigurationAuthentication
        """

        self._authentication = authentication

    @property
    def webhooks(self):
        """Gets the webhooks of this RobotConfiguration.  # noqa: E501


        :return: The webhooks of this RobotConfiguration.  # noqa: E501
        :rtype: RobotConfigurationWebhooks
        """
        return self._webhooks

    @webhooks.setter
    def webhooks(self, webhooks):
        """Sets the webhooks of this RobotConfiguration.


        :param webhooks: The webhooks of this RobotConfiguration.  # noqa: E501
        :type: RobotConfigurationWebhooks
        """

        self._webhooks = webhooks

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RobotConfiguration):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RobotConfiguration):
            return True

        return self.to_dict() != other.to_dict()
